import { useCallback, useEffect, useRef, useState } from 'react'
import type { MessageCommandProposal } from '../../../../shared/command-proposal'
import type { CommandPreparationResult } from '../../../../shared/command-preparation'
type State = { status:'unbound'|'reading'|'selected'|'ready'|'executing'|'finished'|'cancelled'|'timed_out'|'conflict'|'error'; result?: Extract<CommandPreparationResult,{status:'selected'}>['info']; preparedId?: string; executionId?: string; output: string; exitCode?: number; error?: string }
export function useCommandPreparation(proposal: MessageCommandProposal | null): { state: State; select: () => Promise<void>; prepare: () => Promise<void>; execute: () => Promise<void>; cancel: () => Promise<void>; release: () => Promise<void> } {
  const [state,setState]=useState<State>({status:'unbound', output:''}); const generation=useRef(0); const grant=useRef<string|null>(null)
  const source = proposal && { conversationId:proposal.conversationId, requestId:proposal.requestId, assistantId:proposal.assistantId, callId:proposal.callId, snapshotId:proposal.snapshotId, template:proposal.template as 'npm_typecheck' }
  const release=useCallback(async()=>{ const id=grant.current; grant.current=null; if(id) await window.api.releaseCommandDirectory(id) },[])
  const message = (error: unknown): string => error instanceof Error ? error.message.slice(0, 500) : '操作失败，请重试'
  const select=useCallback(async()=>{ if(!source) return; const n=++generation.current; setState({status:'reading',output:''}); try { const r=await window.api.selectCommandDirectory(source, crypto.randomUUID()); if(n!==generation.current) { if(r.status==='selected') await window.api.releaseCommandDirectory(r.info.grantId); return } if(r.status==='selected') { grant.current=r.info.grantId; setState({status:'selected',result:r.info,output:''}) } else if(r.status==='cancelled') setState({status: grant.current?'selected':'unbound',output:''}); else if(r.status==='error') setState({status:'error',error:r.error,output:''}) } catch (error) { if(n===generation.current) setState({status:'error',error:message(error),output:''}) } },[source])
  const prepare=useCallback(async()=>{ if(!source||!grant.current) return; try { const r=await window.api.prepareCommand(source,grant.current,crypto.randomUUID()); if(r.status==='ready') setState(s=>({...s,status:'ready',preparedId:r.preparedId})); else if(r.status==='conflict'||r.status==='expired') { await release(); setState({status:'conflict',error:r.error,output:''}) } else if(r.status==='error') setState({status:'error',error:r.error,output:''}) } catch (error) { setState({status:'error',error:message(error),output:''}) } },[source,release])
  const execute=useCallback(async()=>{ if(!source||!state.preparedId||state.status!=='ready') return; try { const r=await window.api.startCommandExecution({source,preparedId:state.preparedId,confirmationId:crypto.randomUUID()}); if(r.status==='started') setState(s=>({...s,status:'executing',executionId:r.executionId,preparedId:undefined})); else setState(s=>({...s,status:'error',error:r.error,preparedId:undefined})) } catch (error) { setState(s=>({...s,status:'error',error:message(error),preparedId:undefined})) } },[source,state.preparedId,state.status])
  const cancel=useCallback(async()=>{ if(state.executionId) await window.api.cancelCommandExecution(state.executionId) },[state.executionId])
  // The subscription updates state only when the main process emits an execution event.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>window.api.onCommandExecutionEvent(event=>setState(s=>{ if(s.executionId && s.executionId!==event.executionId) return s; if(event.status==='started') return {...s,status:'executing',executionId:event.executionId}; if(event.status==='output') return {...s,output:s.output+event.text}; if(event.status==='finished') return {...s,status:'finished',exitCode:event.exitCode}; return {...s,status:event.status,error:event.error} })),[])
  // Reset transient authorization when the proposal changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{ generation.current++; void release(); setState({status:'unbound',output:''}); },[proposal?.assistantId, proposal?.requestId, release])
  useEffect(()=>()=>{ if(state.executionId && ['executing'].includes(state.status)) void window.api.cancelCommandExecution(state.executionId) },[state.executionId,state.status])
  return { state, select, prepare, execute, cancel, release }
}
