#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <atomic>
#include <cerrno>
#include <cstdint>
#include <cstdlib>
#include <mutex>
#include <string>
#include <vector>

namespace {
class Handle {
 public:
  explicit Handle(HANDLE value = nullptr) : value_(value) {}
  ~Handle() { reset(); }
  Handle(const Handle&) = delete;
  Handle& operator=(const Handle&) = delete;
  HANDLE get() const { return value_; }
  bool valid() const { return value_ && value_ != INVALID_HANDLE_VALUE; }
  void reset(HANDLE value = nullptr) {
    if (valid()) CloseHandle(value_);
    value_ = value;
  }
 private:
  HANDLE value_;
};

struct Host {
  HANDLE output;
  HANDLE input;
  HANDLE job;
  std::mutex outputMutex;
  std::atomic<bool> stopped{false};
  std::atomic<bool> closingControl{false};
  std::atomic<bool> outputFailed{false};
  std::atomic<bool> readerFailed{false};
};

bool writeFrame(Host& host, const std::string& json) {
  std::lock_guard<std::mutex> lock(host.outputMutex);
  const std::string line = json + "\n";
  size_t offset = 0;
  while (offset < line.size()) {
    DWORD written = 0;
    if (!WriteFile(host.output, line.data() + offset,
                   static_cast<DWORD>(line.size() - offset), &written, nullptr) ||
        written == 0) {
      host.outputFailed = true;
      host.stopped = true;
      if (host.job) TerminateJobObject(host.job, 125);
      return false;
    }
    offset += written;
  }
  return true;
}

std::string base64(const unsigned char* bytes, size_t size) {
  static const char alphabet[] =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  std::string result;
  result.reserve(((size + 2) / 3) * 4);
  for (size_t i = 0; i < size; i += 3) {
    uint32_t bits = static_cast<uint32_t>(bytes[i]) << 16;
    if (i + 1 < size) bits |= static_cast<uint32_t>(bytes[i + 1]) << 8;
    if (i + 2 < size) bits |= bytes[i + 2];
    result += alphabet[(bits >> 18) & 63];
    result += alphabet[(bits >> 12) & 63];
    result += i + 1 < size ? alphabet[(bits >> 6) & 63] : '=';
    result += i + 2 < size ? alphabet[bits & 63] : '=';
  }
  return result;
}

std::wstring quoteArgument(const std::wstring& argument) {
  std::wstring result = L"\"";
  size_t backslashes = 0;
  for (wchar_t ch : argument) {
    if (ch == L'\\') { ++backslashes; continue; }
    result.append(ch == L'\"' ? backslashes * 2 + 1 : backslashes, L'\\');
    result += ch;
    backslashes = 0;
  }
  result.append(backslashes * 2, L'\\');
  result += L'\"';
  return result;
}

bool treeExited(HANDLE job, DWORD timeoutMs = 3000) {
  const ULONGLONG deadline = GetTickCount64() + timeoutMs;
  do {
    JOBOBJECT_BASIC_ACCOUNTING_INFORMATION info{};
    if (!QueryInformationJobObject(job, JobObjectBasicAccountingInformation,
                                  &info, sizeof(info), nullptr)) return false;
    if (info.ActiveProcesses == 0) return true;
    Sleep(20);
  } while (GetTickCount64() < deadline);
  return false;
}

int reportError(Host& host, const char* action, DWORD error, bool exited) {
  // Diagnostic text is generated by the host; no child text enters this frame.
  writeFrame(host, "{\"type\":\"error\",\"message\":\"" +
                       std::string(action) + " (Windows error " +
                       std::to_string(error) + ")\",\"treeExited\":" +
                       (exited ? "true}" : "false}"));
  return 1;
}

struct Reader {
  Host* host;
  HANDLE pipe;
  const char* stream;
};

DWORD WINAPI readOutput(LPVOID argument) {
  auto& reader = *static_cast<Reader*>(argument);
  unsigned char bytes[16384];
  while (true) {
    DWORD count = 0;
    if (!ReadFile(reader.pipe, bytes, sizeof(bytes), &count, nullptr)) {
      if (GetLastError() != ERROR_BROKEN_PIPE) reader.host->readerFailed = true;
      return 0;
    }
    if (count == 0) return 0;
    if (!writeFrame(*reader.host,
                    "{\"type\":\"output\",\"stream\":\"" +
                        std::string(reader.stream) + "\",\"data\":\"" +
                        base64(bytes, count) + "\"}")) return 0;
  }
}

DWORD WINAPI readControl(LPVOID argument) {
  auto& host = *static_cast<Host*>(argument);
  std::string line;
  char ch;
  DWORD count = 0;
  while (!host.closingControl) {
    if (!ReadFile(host.input, &ch, 1, &count, nullptr) || count == 0) {
      if (!host.closingControl) {
        host.stopped = true;
        TerminateJobObject(host.job, 125);
      }
      return 0;
    }
    if (ch == '\n') {
      if (line == "stop" || line == "stop\r") {
        host.stopped = true;
        TerminateJobObject(host.job, 125);
        return 0;
      }
      line.clear();
    } else if (line.size() < 128) {
      line += ch;
    }
  }
  return 0;
}

bool joinThread(HANDLE thread, DWORD waitMs, bool cancel) {
  if (!thread) return true;
  if (WaitForSingleObject(thread, waitMs) == WAIT_OBJECT_0) return true;
  if (!cancel) return false;
  // Repeat cancellation to cover a thread entering ReadFile concurrently.
  for (int attempt = 0; attempt < 20; ++attempt) {
    CancelSynchronousIo(thread);
    if (WaitForSingleObject(thread, 50) == WAIT_OBJECT_0) return true;
  }
  return false;
}

bool absolutePath(const std::wstring& value) {
  return (value.size() >= 3 && value[1] == L':' &&
          (value[2] == L'\\' || value[2] == L'/')) ||
         (value.size() >= 2 && value[0] == L'\\' && value[1] == L'\\');
}

int run(int argc, wchar_t** argv, Host& host) {
  const int separator = 5;
  const int programIndex = separator + 1;
  if (argc < 7 || std::wstring(argv[1]) != L"--cwd" ||
      std::wstring(argv[3]) != L"--timeout-ms" || argc <= programIndex ||
      std::wstring(argv[separator]) != L"--" ||
      !absolutePath(argv[2]) || !absolutePath(argv[programIndex])) {
    return reportError(host, "Invalid command-host arguments", ERROR_INVALID_PARAMETER, true);
  }
  wchar_t* end = nullptr;
  errno = 0;
  const unsigned long timeout = wcstoul(argv[4], &end, 10);
  if (errno || !*argv[4] || *end || argv[4][0] == L'-' || timeout == 0 ||
      timeout > 86400000UL) {
    return reportError(host, "Invalid timeout", ERROR_INVALID_PARAMETER, true);
  }
  std::wstring command;
  for (int i = programIndex; i < argc; ++i) {
    if (i > programIndex) command += L' ';
    command += quoteArgument(argv[i]);
  }
  if (command.size() >= 32767) {
    return reportError(host, "Command line exceeds Windows limit", ERROR_INVALID_PARAMETER, true);
  }

  Handle job(CreateJobObjectW(nullptr, nullptr));
  if (!job.valid()) return reportError(host, "CreateJobObject", GetLastError(), true);
  host.job = job.get();
  JOBOBJECT_EXTENDED_LIMIT_INFORMATION limits{};
  limits.BasicLimitInformation.LimitFlags = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;
  if (!SetInformationJobObject(job.get(), JobObjectExtendedLimitInformation,
                               &limits, sizeof(limits))) {
    return reportError(host, "SetInformationJobObject", GetLastError(), true);
  }

  SECURITY_ATTRIBUTES inherit{sizeof(inherit), nullptr, TRUE};
  HANDLE stdoutReadRaw = nullptr, stdoutWriteRaw = nullptr;
  if (!CreatePipe(&stdoutReadRaw, &stdoutWriteRaw, &inherit, 0)) {
    return reportError(host, "Create stdout pipe", GetLastError(), true);
  }
  Handle stdoutRead(stdoutReadRaw), stdoutWrite(stdoutWriteRaw);
  HANDLE stderrReadRaw = nullptr, stderrWriteRaw = nullptr;
  if (!CreatePipe(&stderrReadRaw, &stderrWriteRaw, &inherit, 0)) {
    return reportError(host, "Create stderr pipe", GetLastError(), true);
  }
  Handle stderrRead(stderrReadRaw), stderrWrite(stderrWriteRaw);
  if (!SetHandleInformation(stdoutRead.get(), HANDLE_FLAG_INHERIT, 0) ||
      !SetHandleInformation(stderrRead.get(), HANDLE_FLAG_INHERIT, 0)) {
    return reportError(host, "Protect output readers", GetLastError(), true);
  }
  Handle nullInput(CreateFileW(L"NUL", GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE,
                              &inherit, OPEN_EXISTING, 0, nullptr));
  if (!nullInput.valid()) return reportError(host, "Open NUL stdin", GetLastError(), true);

  SIZE_T attributeSize = 0;
  InitializeProcThreadAttributeList(nullptr, 2, 0, &attributeSize);
  std::vector<unsigned char> attributes(attributeSize);
  auto list = reinterpret_cast<LPPROC_THREAD_ATTRIBUTE_LIST>(attributes.data());
  if (!InitializeProcThreadAttributeList(list, 2, 0, &attributeSize)) {
    return reportError(host, "Initialize process attributes", GetLastError(), true);
  }
  HANDLE inherited[] = {nullInput.get(), stdoutWrite.get(), stderrWrite.get()};
  HANDLE jobHandle = job.get();
  const bool attributesValid =
      UpdateProcThreadAttribute(list, 0, PROC_THREAD_ATTRIBUTE_JOB_LIST, &jobHandle,
                                sizeof(jobHandle), nullptr, nullptr) &&
      UpdateProcThreadAttribute(list, 0, PROC_THREAD_ATTRIBUTE_HANDLE_LIST, inherited,
                                sizeof(inherited), nullptr, nullptr);
  if (!attributesValid) {
    DWORD error = GetLastError();
    DeleteProcThreadAttributeList(list);
    return reportError(host, "Bind job and inherited handles", error, true);
  }

  STARTUPINFOEXW startup{};
  startup.StartupInfo.cb = sizeof(startup);
  startup.StartupInfo.dwFlags = STARTF_USESTDHANDLES;
  startup.StartupInfo.hStdInput = nullInput.get();
  startup.StartupInfo.hStdOutput = stdoutWrite.get();
  startup.StartupInfo.hStdError = stderrWrite.get();
  startup.lpAttributeList = list;
  PROCESS_INFORMATION info{};
  // The main process supplies a sanitized environment when it starts this host.
  BOOL created = CreateProcessW(argv[programIndex], command.data(), nullptr, nullptr, TRUE,
                                 EXTENDED_STARTUPINFO_PRESENT | CREATE_SUSPENDED |
                                     CREATE_NO_WINDOW,
                                 nullptr, argv[2], &startup.StartupInfo, &info);
  DWORD creationError = created ? 0 : GetLastError();
  DeleteProcThreadAttributeList(list);
  stdoutWrite.reset();
  stderrWrite.reset();
  nullInput.reset();
  if (!created) return reportError(host, "Create contained process", creationError, treeExited(job.get()));
  Handle process(info.hProcess), primaryThread(info.hThread);
  Reader stdoutReader{&host, stdoutRead.get(), "stdout"};
  Reader stderrReader{&host, stderrRead.get(), "stderr"};
  DWORD launchError = 0;
  const char* launchAction = "Create command-host threads";
  Handle stdoutThread(CreateThread(nullptr, 0, readOutput, &stdoutReader, 0, nullptr));
  if (!stdoutThread.valid()) launchError = GetLastError();
  Handle stderrThread(CreateThread(nullptr, 0, readOutput, &stderrReader, 0, nullptr));
  if (!stderrThread.valid() && launchError == 0) launchError = GetLastError();
  Handle controlThread(CreateThread(nullptr, 0, readControl, &host, 0, nullptr));
  if (!controlThread.valid() && launchError == 0) launchError = GetLastError();
  if (launchError == 0 && !writeFrame(host, "{\"type\":\"started\",\"pid\":" +
                               std::to_string(info.dwProcessId) + "}")) {
    launchError = ERROR_BROKEN_PIPE;
    launchAction = "Write started frame";
  } else if (launchError == 0 && !host.stopped &&
             ResumeThread(primaryThread.get()) == static_cast<DWORD>(-1) && !host.stopped) {
    launchError = GetLastError();
    launchAction = "Resume contained process";
  }
  primaryThread.reset();

  DWORD exitCode = 1;
  DWORD waitError = 0;
  if (launchError == 0) {
    DWORD waited = WaitForSingleObject(process.get(), static_cast<DWORD>(timeout));
    if (waited == WAIT_TIMEOUT) {
      host.stopped = true;
      TerminateJobObject(job.get(), 124);
    } else if (waited != WAIT_OBJECT_0) {
      waitError = GetLastError();
    }
  }
  if (!GetExitCodeProcess(process.get(), &exitCode)) waitError = GetLastError();
  // Root exit also ends background descendants. No breakaway flag is granted.
  if (!TerminateJobObject(job.get(), launchError ? 126 :
                          (exitCode == STILL_ACTIVE ? (host.stopped ? 125 : 126) : exitCode))) {
    waitError = GetLastError();
  }
  const bool exited = treeExited(job.get());
  if (WaitForSingleObject(process.get(), 1000) == WAIT_OBJECT_0) {
    if (!GetExitCodeProcess(process.get(), &exitCode)) waitError = GetLastError();
  } else {
    waitError = ERROR_TIMEOUT;
  }
  host.closingControl = true;
  const bool controlJoined = joinThread(controlThread.get(), 0, true);
  const bool stdoutJoined = joinThread(stdoutThread.get(), 1000, true);
  const bool stderrJoined = joinThread(stderrThread.get(), 1000, true);
  if (!controlJoined || !stdoutJoined || !stderrJoined) {
    reportError(host, "Command-host thread shutdown unconfirmed", ERROR_TIMEOUT, exited);
    // No stack-owned thread context may outlive this function.
    ExitProcess(1);
  }
  if (launchError) return reportError(host, launchAction, launchError, exited);
  if (waitError) return reportError(host, "Process wait or job termination", waitError, exited);
  if (host.readerFailed) return reportError(host, "Command output drain interrupted", ERROR_OPERATION_ABORTED, exited);
  if (host.outputFailed) return 1;
  writeFrame(host, "{\"type\":\"closed\",\"exitCode\":" + std::to_string(exitCode) +
                       ",\"treeExited\":" + (exited ? "true" : "false") +
                       ",\"stopped\":" + (host.stopped ? "true}" : "false}"));
  return host.outputFailed ? 1 : 0;
}
}  // namespace

int wmain(int argc, wchar_t** argv) {
  Host host{GetStdHandle(STD_OUTPUT_HANDLE), GetStdHandle(STD_INPUT_HANDLE), nullptr};
  try {
    if (argc == 2 && std::wstring(argv[1]) == L"--capabilities") {
      return writeFrame(host, "{\"protocol\":1,\"atomicJob\":true}") ? 0 : 1;
    }
    return run(argc, argv, host);
  } catch (...) {
    // Any job handle owned by run has closed and requested kernel termination.
    host.job = nullptr;
    return reportError(host, "Unexpected command-host failure", ERROR_UNHANDLED_EXCEPTION, false);
  }
}
